[myhosts]
54.87.6.14 ansible_user=ec2-user ansible_ssh_private_key_file=/Users/jgorle/Desktop/test.pem
#34.202.236.104 ansible_user=ec2-user ansible_ssh_private_key_file=/Users/jgorle/Desktop/test.pem
