- name: Vars Prompt Example
  hosts: webservers
  vars_prompt:
    - name: "pkg_name"
      prompt: "Enter the package to install"
      private: no
    - name: "server_port"
      prompt: "Enter server port"
      private: no
  tasks:
    - name: Install prompted package
      ansible.builtin.yum:
        name: "{{ pkg_name }}"
        state: present

    - name: Show prompted port
      ansible.builtin.debug:
        msg: "Server will run on port {{ server_port }}"
